# Generated by Django 5.2.13 on 2026-04-19 18:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.IntegerField(help_text='Steam application ID (unique identifier from Steam Store).', unique=True)),
                ('name', models.CharField(help_text='Title of the game.', max_length=255)),
                ('release_date', models.DateField(blank=True, help_text='Official release date on Steam (YYYY-MM-DD).', null=True)),
                ('developer', models.CharField(blank=True, default='', help_text='Developer name(s); semicolon-delimited if multiple.', max_length=255)),
                ('publisher', models.CharField(blank=True, default='', help_text='Publisher name(s); semicolon-delimited if multiple.', max_length=255)),
                ('platforms', models.CharField(blank=True, default='', help_text="Supported platforms (e.g. 'windows;mac;linux').", max_length=100)),
                ('required_age', models.IntegerField(default=0, help_text='Minimum required age (PEGI standard); 0 means unrated.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(21)])),
                ('english', models.BooleanField(default=True, help_text='Whether the game supports English.')),
                ('categories', models.TextField(blank=True, default='', help_text='Semicolon-delimited Steam categories.')),
                ('genres', models.TextField(blank=True, default='', help_text="Semicolon-delimited Steam genres (e.g. 'Action;RPG').")),
                ('steamspy_tags', models.TextField(blank=True, default='', help_text='Semicolon-delimited SteamSpy community tags.')),
                ('achievements', models.IntegerField(default=0, help_text='Total number of Steam achievements available.', validators=[django.core.validators.MinValueValidator(0)])),
                ('positive_ratings', models.IntegerField(default=0, help_text='Number of positive user ratings (from SteamSpy).', validators=[django.core.validators.MinValueValidator(0)])),
                ('negative_ratings', models.IntegerField(default=0, help_text='Number of negative user ratings (from SteamSpy).', validators=[django.core.validators.MinValueValidator(0)])),
                ('average_playtime', models.IntegerField(default=0, help_text='Average playtime in minutes (from SteamSpy).', validators=[django.core.validators.MinValueValidator(0)])),
                ('median_playtime', models.IntegerField(default=0, help_text='Median playtime in minutes (from SteamSpy).', validators=[django.core.validators.MinValueValidator(0)])),
                ('owners', models.CharField(blank=True, default='', help_text="Estimated ownership range (e.g. '10000000-20000000').", max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Current price in USD; 0.00 indicates a free-to-play title.', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'games',
                'ordering': ['-positive_ratings'],
                'indexes': [models.Index(fields=['appid'], name='games_appid_2d06b6_idx'), models.Index(fields=['name'], name='games_name_eb11e6_idx'), models.Index(fields=['release_date'], name='games_release_779b0a_idx'), models.Index(fields=['price'], name='games_price_eccac7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], help_text='Numeric rating from 1 (worst) to 10 (best).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('title', models.CharField(help_text='Short title or headline for the review.', max_length=200)),
                ('body', models.TextField(help_text='Full review text.')),
                ('hours_played', models.FloatField(blank=True, help_text='Hours the reviewer has played this game (optional).', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('recommended', models.BooleanField(default=True, help_text='Whether the reviewer recommends this game.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(help_text='The game being reviewed.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='games.game')),
                ('user', models.ForeignKey(help_text='The user who submitted this review.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['game', 'rating'], name='reviews_game_id_002d57_idx'), models.Index(fields=['user'], name='reviews_user_id_79db63_idx')],
                'unique_together': {('game', 'user')},
            },
        ),
    ]
